{% set name = "nene" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nene-{{ version }}.tar.gz
  sha256: 5f37ef9dfbd6dd24e969bfb6bbe3b365e31ec0d82805e9cbf2ef06a364de5ab6

build:
  number: 0
  noarch: python
  entry_points:
    - nene = nene.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - click >=8
    - jinja2 >=3.0
    - livereload >=2.6
    - markdown-it-py >=2.0
    - mdit-py-plugins >=0.3
    - pyyaml >=5.4
    - rich >=10.9

test:
  imports:
    - nene
  commands:
    - pip check
    - nene --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://nene.leouieda.com
  summary: A no-frills static site generator
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
