{% set name = "nene" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nene-{{ version }}.tar.gz
  sha256: ce04e0612c1b37e8eefef8b13d5b8eca58d03234fce3f17fc0b194c544f0679d

build:
  number: 0
  noarch: python
  entry_points:
    - nene = nene.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - click >=8
    - jinja2 >=3.0
    - livereload >=2.6
    - myst-parser >=0.15.0
    - python >=3.6
    - pyyaml >=5.4
    - rich >=10.9

test:
  imports:
    - nene
  commands:
    - pip check
    - nene --help
  requires:
    - pip

about:
  home: https://nene.leouieda.com
  summary: A no-frills static site generator
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
