{% set name = "nene" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nene-{{ version }}.tar.gz
  sha256: 2c2b7dfd128d8935b03a5bcc84fdb5dd725578243578e96338f5105a6325b95c

build:
  number: 0
  noarch: python
  entry_points:
    - nene = nene.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - click >=8
    - jinja2 >=3.0
    - livereload >=2.6
    - markdown-it-py >=2.0
    - mdit-py-plugins >=0.3
    - pyyaml >=5.4
    - rich >=10.9

test:
  imports:
    - nene
  commands:
    - pip check
    - nene --help
  requires:
    - pip

about:
  home: https://nene.leouieda.com
  summary: A no-frills static site generator
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
